version: "3"

services:
  namenode:
    image: bigdatainf/hadoop-namenode:3.3.5
    container_name: namenode
    restart: always
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - ./data/namenode:/hadoop/dfs/name
      - ./jobs:/app
    working_dir: /app
    environment:
      - CLUSTER_NAME=test
      - HOME=/app
    env_file:
      - ./hadoop.env

  datanode1:
    image: bigdatainf/hadoop-datanode:3.3.5
    container_name: datanode1
    restart: always    
    volumes:
      - ./data/datanode1:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env

  datanode2:
    image: bigdatainf/hadoop-datanode:3.3.5
    container_name: datanode2
    restart: always    
    volumes:
      - ./data/datanode2:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env

  datanode3:
    image: bigdatainf/hadoop-datanode:3.3.5
    container_name: datanode3
    restart: always    
    volumes:
      - ./data/datanode3:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env

  datanode4:
    image: bigdatainf/hadoop-datanode:3.3.5
    container_name: datanode4
    restart: always    
    volumes:
      - ./data/datanode4:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env

  datanode5:
    image: bigdatainf/hadoop-datanode:3.3.5
    container_name: datanode5
    restart: always    
    volumes:
      - ./data/datanode5:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
  
  
