version: '3.7'

services:

# ----------------------------------------------------------------------------------------------
  jupyter:
    image: jupyter/minimal-notebook
    ports:
      - 8888:8888
    command: ["start-notebook.sh",
              "--NotebookApp.token=''",
              "--NotebookApp.password=''"]

# ----------------------------------------------------------------------------------------------
  neo4j:
      hostname: neo4j
      image: neo4j:4.4.17-community
      environment:
          - NEO4J_dbms_mode=SINGLE
          - NEO4J_dbms_connector_bolt_advertised__address=localhost:7687
          - NEO4J_dbms_default__listen__address=0.0.0.0
          - NEO4J_dbms_default__advertised__address=localhost
          - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
          - NEO4J_AUTH=neo4j/password
          - NEO4J_dbms_routing_listen__address=0.0.0.0:7688
      ports:
          - 7474:7474
          - 7473:7473
          - 7687:7687

# ----------------------------------------------------------------------------------------------

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    volumes:
      - ./data/:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - bdi_net

networks:
  bdi_net:
    driver: bridge

# ----------------------------------------------------------------------------------------------

  