version: "3.6"

volumes:
  shared-workspace:
    name: "hadoop-distributed-file-system"
    driver: local

services:

# ----------------------------------------------------------------------------------------------

  jupyterlab:
    image: cbadenes/spark-jupyter:0.0.1
    container_name: jupyterlab
    ports:
      - 8889:8888
    volumes:
      - shared-workspace:/opt/workspace   

# ----------------------------------------------------------------------------------------------

  spark-master:
    image: cbadenes/spark-master:0.0.1
    container_name: spark-master
    ports:
      - 8080:8080
      - 7077:7077
    volumes:
      - shared-workspace:/opt/workspace

  spark-worker-1:
    image: cbadenes/spark-worker:0.0.1
    container_name: spark-worker-1
    environment:
      - SPARK_WORKER_CORES=4
      - SPARK_WORKER_MEMORY=10g
    ports:
      - 4041:4040
      - 18081:18080
    volumes:
      - shared-workspace:/opt/workspace
    depends_on:
      - spark-master

  spark-worker-2:
    image: cbadenes/spark-worker:0.0.1
    container_name: spark-worker-2
    environment:
      - SPARK_WORKER_CORES=4
      - SPARK_WORKER_MEMORY=10g
    ports:
      - 4042:4040
      - 18082:18080
    volumes:
      - shared-workspace:/opt/workspace
    depends_on:
      - spark-master

# ----------------------------------------------------------------------------------------------

  neo4j:
      hostname: neo4j
      image: neo4j:4.4.17-community
      environment:
          - NEO4J_dbms_mode=SINGLE
          - NEO4J_dbms_connector_bolt_advertised__address=localhost:7687
          - NEO4J_dbms_default__listen__address=0.0.0.0
          - NEO4J_dbms_default__advertised__address=localhost
          - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
          - NEO4J_AUTH=neo4j/password
          - NEO4J_dbms_routing_listen__address=0.0.0.0:7688
      ports:
          - 7474:7474
          - 7473:7473
          - 7687:7687

# ----------------------------------------------------------------------------------------------
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    networks:
      - bdi_net
networks:
  bdi_net:
    driver: bridge
