version: "3"

services:
  namenode:
    image: bigdatainf/hadoop-namenode:3.3.5
    container_name: namenode
    restart: always
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - ./data/namenode:/hadoop/dfs/name
      - ./jobs:/app
    working_dir: /app
    environment:
      - CLUSTER_NAME=test
      - HOME=/app
    env_file:
      - ./hadoop.env

  datanode1:
    image: bigdatainf/hadoop-datanode:3.3.5
    container_name: datanode1
    restart: always    
    volumes:
      - ./data/datanode1:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env

  nodemanager1:
    image: bigdatainf/hadoop-nodemanager:3.3.5
    container_name: nodemanager1
    restart: always    
    environment:
      SERVICE_PRECONDITION: "datanode1:9864"
    env_file:
      - ./hadoop.env

  resourcemanager:
    image: bigdatainf/hadoop-resourcemanager:3.3.5
    container_name: resourcemanager
    restart: always
    ports:
      - 8088:8088
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode1:9864"
    env_file:
      - ./hadoop.env

  historyserver:
    image: cbadenes/hadoop-historyserver:3.3.5
    #image: bigdatainf/hadoop-historyserver:3.3.5
    container_name: historyserver
    restart: always
    environment:
      SERVICE_PRECONDITION: "resourcemanager:8088"
    volumes:
      - ./data/historyserver:/hadoop/yarn/timeline
    env_file:
      - ./hadoop.env

  