version: '3'

services: 

# ----------------------------------------------------------------------------------------------
  jupyter:
    image: jupyter/minimal-notebook
    ports:
      - 8888:8888
    command: ["start-notebook.sh",
              "--NotebookApp.token=''",
              "--NotebookApp.password=''"]

# ----------------------------------------------------------------------------------------------
  neo4j:
      hostname: neo4j
      image: neo4j:4.4.17-community
      environment:
          - NEO4J_dbms_mode=SINGLE
          - NEO4J_dbms_connector_bolt_advertised__address=localhost:7687
          - NEO4J_dbms_default__listen__address=0.0.0.0
          - NEO4J_dbms_default__advertised__address=localhost
          - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
          - NEO4J_AUTH=neo4j/password
          - NEO4J_dbms_routing_listen__address=0.0.0.0:7688
      ports:
          - 7474:7474
          # - 7473:7473
          # - 7687:7687

# ----------------------------------------------------------------------------------------------

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    volumes:
      - ./data/:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - bdi_net



# ----------------------------------------------------------------------------------------------

  namenode:
    image: noachuartzt/ibd-g2_hadoop-namenode:3.3.5
    container_name: namenode
    restart: always
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - ./data/namenode:/hadoop/dfs/name
      - ./jobs:/app
    working_dir: /app
    environment:
      - CLUSTER_NAME=test
      - HOME=/app
    env_file:
      - ../hadoop.env

  datanode1:
    image: noachuartzt/ibd-g2_hadoop-datanode:3.3.5
    container_name: datanode1
    restart: always    
    volumes:
      - ./data/datanode1:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ../hadoop.env

  nodemanager1:
    image: noachuartzt/ibd-g2_hadoop-nodemanager:3.3.5
    container_name: nodemanager1
    restart: always    
    environment:
      SERVICE_PRECONDITION: "datanode1:9864"
    env_file:
      - ../hadoop.env

  resourcemanager:
    image: noachuartzt/ibd-g2_hadoop-resourcemanager:3.3.5
    container_name: resourcemanager
    restart: always
    ports:
      - 8088:8088
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode1:9864"
    env_file:
      - ../hadoop.env

  historyserver:
    #image: cbadenes/ibd-g2_hadoop-historyserver:3.3.5
    image: noachuartzt/ibd-g2_hadoop-historyserver:3.3.5
    container_name: historyserver
    restart: always
    environment:
      SERVICE_PRECONDITION: "resourcemanager:8088"
    volumes:
      - ./data/historyserver:/hadoop/yarn/timeline
    env_file:
      - ../hadoop.env

networks:
  bdi_net:
    driver: bridge